### ISSUE TITLE
exTable 对 css 片段的支持不太好。

### ISSUE THREAD

**Issue by Immortal-Sty** [any-block/any-block#164]
## AnyBlock 的效果

![Image](https://github.com/user-attachments/assets/00c102ad-a47e-40ac-a08e-351b450da883)

## Sheets Extended 的效果：

![Image](https://github.com/user-attachments/assets/0a075af0-0b91-4105-b592-8cce90157f8a)

猜测是Sheets Extended 只合并了单元格，而 AnyBlock 更改了更多的样式导致的。

## 图中使用的 css 代码片段

```css
/***************/
/* 表格内自动折行 */
/***************/

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper .cm-active, .markdown-rendered table) {
	word-break: break-all;
}

/********************/
/* 仿 Typora 表格样式 */
/********************/

body.theme-dark {
	/* 表格圆角大小 */
	--table-radius: var(--size-2-3);
	/* 表格按钮颜色 */
	--table-btn-color: #fff;
	/* 表格按钮背景色 */
	--table-btn-bg: #292929;
	/* 表格头背景色 */
	--table-header-bg: #242424;
	/* 表格隔行背景色 */
	--table-alt-line-bg: #242424;
	/* 动画时间 */
	--animation: 200ms var(--anim-motion-smooth);
}

body.theme-light {
	/* 表格圆角大小 */
	--table-radius: var(--size-2-3);
	/* 表格按钮颜色 */
	--table-btn-color: #fff;
	/* 表格按钮背景色 */
	--table-btn-bg: #fff;
	/* 表格头背景色 */
	--table-header-bg: #f4f4f4;
	/* 表格隔行背景色 */
	--table-alt-line-bg: #f4f4f4;
	/* 动画时间 */
	--animation: 200ms var(--anim-motion-smooth);
}

.markdown-rendered table {
	border-collapse: initial;
	border-spacing: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) {
	--table-white-space: break-all;
	width: 100%;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) .table-editor {
	width: 100%;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) .table-col-btn {
	border-top-right-radius: var(--table-radius);
	border-bottom-right-radius: var(--table-radius);
	color: var(--table-btn-color);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) .table-row-btn {
	border-bottom-left-radius: var(--table-radius);
	border-bottom-right-radius: var(--table-radius);
	color: var(--table-btn-color);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) :is(.table-col-btn, .table-row-btn, .table-col-drag-handle:hover, .table-row-drag-handle:hover) {
	transition: var(--animation);
	background-color: var(--table-btn-bg);
	--table-drag-handle-color: var(--table-btn-color);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) :is(tr:hover .table-row-drag-handle, th:hover .table-col-drag-handle) {
	opacity: 1;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) th:first-child:not(:has(:is(.table-row-drag-handle, .table-col-drag-handle):hover)) {
	border-top-left-radius: var(--table-radius);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) th:last-child:not(:has(.table-col-drag-handle:hover)) {
	border-top-right-radius: var(--table-radius);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table):has(.table-col-btn:hover) th:last-child {
	border-top-right-radius: 0;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tr:last-child td:first-child {
	border-bottom-left-radius: var(--table-radius);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table):has(.table-row-btn:hover) tr:last-child td:first-child {
	border-bottom-left-radius: 0;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tr:last-child td:last-child {
	border-bottom-right-radius: var(--table-radius);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table):has(:is(.table-col-btn, .table-row-btn):hover) tr:last-child td:last-child {
	border-bottom-right-radius: 0;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) :is(th, td):not(:first-child) {
	border-left: 0;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tbody td {
	border-top: 0;
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) thead tr {
	background-color: var(--table-header-bg);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tbody tr:nth-of-type(2n) {
	background-color: var(--table-alt-line-bg);
}
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tbody tr:nth-of-type(2n+1) {
	background-color: var(--background-primary);
}
```

**Comment by LincZero** [comment]
dom结构不同的原因吧，肯定是可以用css来改成功的。

关键在于css写得对不对，选择器有没有问题，选择器的权重是不是过低等。

都可以用DevTools调试，找到问题

**Comment by LincZero** [comment]
肯定是改 css，不可能是我这边改程序……

**Comment by LincZero** [comment]
exTable是没thead的，只有tbody，没表头只有表体。

你css把tbody第一行的顶部边框给去掉了

**Comment by Immortal-Sty** [comment]
谢谢，可惜我不会改😂。我还是太菜了，最近才开始学前端，看来要加快进度了。

**Comment by Immortal-Sty** [comment]
学了几天 CSS，成功改好 CSS 了，现在兼容支持所有没有 `<thead>` 的表格。注：该 CSS 片段来自 Obsidian 管方论坛的[该贴子](https://forum-zh.obsidian.md/t/topic/27878)。

代码如下，有需要可以直接拿走：

```css
/********************/
/* 表格编辑行号变窄 */
/********************/

table div.cm-gutters {
	margin-inline-end: 0 !important;
}

/****************/
/* 表格垂直居中 */
/****************/

td {
	vertical-align: middle !important;
}

/******************/
/* 表格内自动折行 */
/******************/

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper .cm-active, .markdown-rendered table) {
	word-break: break-all;
}

/**********************/
/* 仿 Typora 表格样式 */
/**********************/

body.theme-dark {
	/* 表格圆角大小 */
	--table-radius: var(--size-2-3);
	/* 表格按钮颜色 */
	--table-btn-color: #fff;
	/* 表格按钮背景色 */
	--table-btn-bg: #292929;
	/* 表格头背景色 */
	--table-header-bg: #242424;
	/* 表格隔行背景色 */
	--table-alt-line-bg: #242424;
	/* 动画时间 */
	--animation: 200ms var(--anim-motion-smooth);
}

body.theme-light {
	/* 表格圆角大小 */
	--table-radius: var(--size-2-3);
	/* 表格按钮颜色 */
	--table-btn-color: #fff;
	/* 表格按钮背景色 */
	--table-btn-bg: #aed7ff;
	/* 表格头背景色 */
	--table-header-bg: #f4f4f4;
	/* 表格隔行背景色 */
	--table-alt-line-bg: #f4f4f4;
	/* 动画时间 */
	--animation: 200ms var(--anim-motion-smooth);
}

/* 合并表格单元格 */
.ab-note table.ab-table,
.markdown-rendered table {
	border-collapse: initial;
	border-spacing: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) {
	--table-white-space: break-all;
	width: 100%;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) .table-editor {
	width: 100%;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) .table-col-btn {
	border-top-right-radius: var(--table-radius);
	border-bottom-right-radius: var(--table-radius);
	color: var(--table-btn-color);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) .table-row-btn {
	border-bottom-left-radius: var(--table-radius);
	border-bottom-right-radius: var(--table-radius);
	color: var(--table-btn-color);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) :is(.table-col-btn, .table-row-btn, .table-col-drag-handle:hover, .table-row-drag-handle:hover) {
	transition: var(--animation);
	background-color: var(--table-btn-bg);
	--table-drag-handle-color: var(--table-btn-color);
}

/* TODO */
.markdown-rendered table:not(:has(thead)) tr:first-of-type {
	background-color: var(--table-btn-bg);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) :is(tr:hover .table-row-drag-handle, th:hover .table-col-drag-handle) {
	opacity: 1;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) th:first-child:not(:has(:is(.table-row-drag-handle, .table-col-drag-handle):hover)),
.markdown-rendered table:not(:has(thead)) tr:first-child td:first-child:not(:has(:is(.table-row-drag-handle, .table-col-drag-handle):hover)) {
	border-top-left-radius: var(--table-radius);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table:not(:has(thead))) tr:first-of-type td:last-of-type,
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) th:last-child:not(:has(.table-col-drag-handle:hover)) {
	border-top-right-radius: var(--table-radius);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table):has(.table-col-btn:hover) th:last-child {
	border-top-right-radius: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tr:last-child td:first-child {
	border-bottom-left-radius: var(--table-radius);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table):has(.table-row-btn:hover) tr:last-child td:first-child {
	border-bottom-left-radius: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) tr:last-child td:last-child {
	border-bottom-right-radius: var(--table-radius);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table):has(:is(.table-col-btn, .table-row-btn):hover) tr:last-child td:last-child {
	border-bottom-right-radius: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) :is(th, td):not(:first-child) {
	border-left: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table:not(:has(thead))) tbody tr:not(:first-of-type) td,
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table:has(thead)) tbody td {
	border-top: 0;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered) table:not(:has(thead)) tr:first-of-type,
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table) thead tr {
	background-color: var(--table-header-bg);
	font-weight: bold;
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered) table:not(:has(thead)) tbody tr:nth-of-type(2n+1),
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table:has(thead)) tbody tr:nth-of-type(2n) {
	background-color: var(--table-alt-line-bg);
}

:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered) table:not(:has(thead)) tbody tr:nth-of-type(2n),
:is(.markdown-source-view.mod-cm6 .cm-table-widget .table-wrapper, .markdown-rendered table:has(thead)) tbody tr:nth-of-type(2n+1) {
	background-color: var(--background-primary);
}
```
